// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChO26WmCVbyq4XJCrNxLx8VAnVQgUKWpI',
    appId: '1:705949305400:web:b0792b2f445fac7b9574cd',
    messagingSenderId: '705949305400',
    projectId: 'mock-dc92d',
    authDomain: 'mock-dc92d.firebaseapp.com',
    storageBucket: 'mock-dc92d.appspot.com',
    measurementId: 'G-KYT8RBRTT2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtkyhjeBvHVlTfFmx8CccHNu9XbiQkI0Y',
    appId: '1:705949305400:android:7419cfc7a66d5d2a9574cd',
    messagingSenderId: '705949305400',
    projectId: 'mock-dc92d',
    storageBucket: 'mock-dc92d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCweay8xEOIyQuBnxXTd4XxvLhqOhR2az0',
    appId: '1:705949305400:ios:f70e0ac5ca65d2e19574cd',
    messagingSenderId: '705949305400',
    projectId: 'mock-dc92d',
    storageBucket: 'mock-dc92d.appspot.com',
    iosBundleId: 'com.example.mock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCweay8xEOIyQuBnxXTd4XxvLhqOhR2az0',
    appId: '1:705949305400:ios:77a7a429fd11ecde9574cd',
    messagingSenderId: '705949305400',
    projectId: 'mock-dc92d',
    storageBucket: 'mock-dc92d.appspot.com',
    iosBundleId: 'com.example.mock.RunnerTests',
  );
}
